# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: docker:17.05.0-ce-git

    steps:
      - checkout

      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
          docker build -t svanscho/rpi-radio:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push svanscho/rpi-radio:$TAG